name = "Peaks"
uuid = "18e31ff7-3703-566c-8e60-38913d67486b"
authors = ["Allen Hill <allenofthehills@gmail.com>"]
version = "0.1.0"

[deps]
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

